### ISSUE TITLE
stop passing JS objects to redis

### ISSUE THREAD

**Issue by rcmiller** [uid/gitstream#6]
Now getting this warning from node_redis:

node_redis: Deprecated: The HSET command contains a argument of type Object.
This is converted to "[object Object]" by using .toString() now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.

Seems to appear as a result of the exerciseChanged event;
the newExercise it's trying to set is { newExercise: '', setHash: true }

**Comment by javier-solis** [comment]
Resolved by the removal of Redis.
